apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: superset
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - image: apache/superset
        name: superset
        ports:
        - containerPort: 8088
          name: superset
