apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: default
  labels:
    app: superset
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: devopsajit85/superset  # Replace with your actual image name
          ports:
            - containerPort: 8088  # Port that Superset is exposed on
          env:
            - name: SUPERSET_DATABASE_URI
              value: "sqlite:////app/superset/superset.db"  # Example database URI
            # Add any additional environment variables needed for your application
          resources:  # Optional resource requests/limits
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
