apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Number of NGINX replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # NGINX image
        ports:
        - containerPort: 80  # Port on which NGINX listens
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d  # Mount path for NGINX configuration
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config  # Reference to the ConfigMap for custom configuration
