apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Change to LoadBalancer or NodePort as needed
  selector:
    app: nginx  # Selects the NGINX pods
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port on the NGINX pod
