name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3         
        

      - name: Set up Docker
        run: |
          # Ensure Docker is running and available
          docker --version

      - name: Build Docker containers
        run: |
          # Navigate to the application directory
          cd /home/sambhav/Downloads/superset-master

          # Build the Docker containers from the Dockerfile(s)
          docker-compose -f docker-compose.yml build

          # Stop and remove any running containers
          docker-compose -f docker-compose.yml down

          # Start the containers in detached mode
          docker-compose -f docker-compose.yml up -d

      - name: Verify Deployment
        run: |
          # Optionally, you can check if the application is running
          curl -f http://localhost:your_port || (echo "Application not running" && exit 1)
